# Generated by Django 5.2.7 on 2025-10-31 16:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('definicion_problema', models.TextField(blank=True, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=100)),
                ('run', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rbd', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_dependencia', models.CharField(blank=True, choices=[('Municipal', 'Municipal'), ('Particular Subvencionado', 'Particular Subvencionado'), ('Particular Pagado', 'Particular Pagado'), ('Corporación', 'Corporación')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedenteSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_prev', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_parto', models.CharField(blank=True, max_length=50, null=True)),
                ('asistencia_parto', models.BooleanField(default=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('antecedentes_embarazo', models.TextField(blank=True, null=True)),
                ('hospitalizaciones', models.BooleanField(default=False)),
                ('vacunas', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_salud', to='core.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistadores', to='core.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(blank=True, max_length=30, null=True)),
                ('anio_escolar', models.PositiveIntegerField(blank=True, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='Interno', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidad')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.establecimiento')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=100)),
                ('nombre_social', models.CharField(blank=True, max_length=100, null=True)),
                ('run', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('lengua_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('lengua_uso', models.CharField(blank=True, max_length=50, null=True)),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.apoderado')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.curso')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionIntegral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], default='En proceso', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_integrales', to='core.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='evaluacion_integral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='core.evaluacionintegral'),
        ),
        migrations.CreateModel(
            name='EvaluacionPsicopedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluador', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evaluacion_integral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_psicopedagogica', to='core.evaluacionintegral')),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiaApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('aplicada', models.BooleanField(default=False)),
                ('exitosa', models.BooleanField(default=False)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias_apoyo', to='core.evaluacionpsicopedagogica')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=20)),
                ('profesional', models.CharField(max_length=100)),
                ('recibido', models.BooleanField(default=False)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoyos_adicionales', to='core.evaluacionpsicopedagogica')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('fecha_reevaluacion', models.DateField(blank=True, null=True)),
                ('motivo_consulta', models.CharField(max_length=255)),
                ('descripcion_diagnostico', models.TextField(blank=True, null=True)),
                ('estado_salud_general', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluacion_integral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_salud', to='core.evaluacionintegral')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_salud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrevista', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('relacion_estudiante', models.CharField(max_length=50)),
                ('presencia', models.CharField(blank=True, max_length=100, null=True)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informantes', to='core.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='InformeFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('motivo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Reevaluación', 'Reevaluación')], max_length=50)),
                ('diagnostico_nee', models.TextField(blank=True, null=True)),
                ('trabajo_colaborativo', models.TextField(blank=True, null=True)),
                ('apoyos_requeridos_hogar', models.TextField(blank=True, null=True)),
                ('acuerdos_compromisos', models.TextField(blank=True, null=True)),
                ('evaluacion_integral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_familia', to='core.evaluacionintegral')),
            ],
        ),
        migrations.CreateModel(
            name='InformeFamiliaAmbito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('Pedagógico', 'Pedagógico'), ('Social/Afectivo', 'Social/Afectivo')], max_length=30)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('necesidades_apoyo', models.TextField(blank=True, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambitos', to='core.informefamilia')),
            ],
        ),
        migrations.CreateModel(
            name='InformeFamiliaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_identidad', models.CharField(blank=True, max_length=120, null=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('rol_cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='core.informefamilia')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformeFamiliaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='core.informefamilia')),
            ],
        ),
        migrations.CreateModel(
            name='InformeFamiliaReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_identidad', models.CharField(blank=True, max_length=120, null=True)),
                ('rut_pasaporte', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_social', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relacion', models.CharField(blank=True, max_length=60, null=True)),
                ('es_apoderado_titular', models.BooleanField(default=False)),
                ('es_apoderado_suplente', models.BooleanField(default=False)),
                ('poder_simple', models.BooleanField(default=False)),
                ('en_presencia_de', models.CharField(blank=True, max_length=200, null=True)),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apoderado')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to='core.informefamilia')),
            ],
        ),
        migrations.CreateModel(
            name='InformeFamiliaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.informefamilia')),
            ],
        ),
        migrations.CreateModel(
            name='SubdimensionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('valor', models.PositiveSmallIntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.evaluacionpsicopedagogica')),
            ],
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsector', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('destacado', 'Destacado'), ('dificultad', 'Dificultad')], max_length=50)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsectores', to='core.evaluacionpsicopedagogica')),
            ],
        ),
    ]
