# Generated by Django 4.2.25 on 2025-11-06 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anamnesis_pdf_generado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('periodo', models.CharField(blank=True, help_text='Ej: Primer semestre, Segundo semestre, etc.', max_length=50, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pie', to='core.curso')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_pie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoColaborativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Co-enseñanza', 'Co-enseñanza'), ('Planificación compartida', 'Planificación compartida'), ('Reunión de equipo', 'Reunión de equipo'), ('Trabajo con familia', 'Trabajo con familia'), ('Trabajo con comunidad', 'Trabajo con comunidad'), ('Otro', 'Otro')], max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_colaborativos', to='core.registropie')),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionPIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_curso', models.TextField(blank=True, null=True)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('necesidades_apoyo', models.TextField(blank=True, null=True)),
                ('estrategias_generales', models.TextField(blank=True, null=True)),
                ('recursos_apoyo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planificacion', to='core.registropie')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogroAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('logros', models.TextField(blank=True, null=True)),
                ('dificultades', models.TextField(blank=True, null=True)),
                ('estrategias_utilizadas', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estudiante')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='core.registropie')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionPIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('proyecciones', models.TextField(blank=True, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='core.registropie')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Profesor Regular', 'Profesor Regular'), ('Educador Diferencial', 'Educador Diferencial'), ('Psicólogo', 'Psicólogo'), ('Fonoaudiólogo', 'Fonoaudiólogo'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'), ('Asistente de Aula', 'Asistente de Aula'), ('Coordinador PIE', 'Coordinador PIE'), ('Otro', 'Otro')], max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_aula', to='core.registropie')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('participantes', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_comunidad', to='core.registropie')),
            ],
        ),
    ]
